= Q-Behave
Marek Smigielski

The +Q-Behave+ is Arduino compatible C++ library for machine learning applications. 
It implements Q-Learning algorithm as an action quantifier for machine state. This means
that you can expect your program to react to user inputs in adaptive way. Instead 
of binary reasoning that is usaly hardcoded by developer, machine will follow simple 
learning process starting from fully random behaviour converting over time into fulfilling 
user expectations.    


== Example

Using this library is very simple. In fact even six year old girl had no problems 
 teaching Arduino how to distinguish colors. Watch this video to see full learning process:
 
video::92062034[vimeo, 400, 300]

In this process we had three buttons and RGB diode. No mixing of colors was used so this 
setup acts as three seperate diodes. 
The aim of the teacher was to pick one color and assign it to the button on the breadboard. 
Whenever Arduino shows correct color after pushing the button, the teacher accepts it 
by pressing the reward button.

As shown in this video, learning time is very short. 60 second to learn a basic pattern with acceptable
level of success was enough.
   

== Starting up

=== Hardware

=== Libraries

== Possiblities

== License

This work is licensed as GPL software. See LICENSE file for full text.

If you need other license or would like to get support, please contact me at marek.smigielski(at)gmail.com