= Q-Behave
Marek Smigielski

+Q-Behave+ is machine learning library written in C++ compatible with Arduino and other embeded devices. 
The idea behind machine learning is to allow your device to acquire patterns based on user interactions. This is achieved without the need to program them beforehand. 

To illustrate this concept take RGB diode with only one button as an example. After pressing the button the user expects to see diode flash with some color. Next user will have different color in mind when pressing the button. In a conventional way the system cannot be programmed to guess user intention on which color to show.

When we put Q-Behave as a processor between interaction (pressing a button)
and state (flashing the diode) the device will choose one of possible states based on prior experience gained from user interaction. So when the user expects to see green light and instead the led flashes a different color, the user presses the button immediately again to finally get the desired color. This way the user informs the processor that he/she was expecting a different state of the diode. After several trials the device responds with a correct color right the first time because it learns what the user expects from it. 

Utilizing this technique one program can behave differently and adapt to different users. In fact the same rule applies when user changes his mind thus forcing the device 
to learn the new behaviour. After some trials with the old color the program will adapt to new rules and satisfy user expectations without the need to reprogram it.

 
END OF NEW VERSION

 

interactionsde --> processor --> action


The +Q-Behave+ is Arduino compatible C++ library for machine learning applications. 
It implements Q-Learning algorithm as an action quantifier for state machine. This means
that you can expect from your program to react to user inputs in adaptive way. Instead 
of binary reasoning that is usaly hardcoded by developer, machine will follow simple 
learning process starting from fully random behaviour converting over time into fulfilling 
user expectations.    


== Example

Using of this library is very simple. In fact even six year old girl had no problems 
with teching Arduino how to distinguish colors. Watch this video to see full learning process:
 
video::92062034[vimeo, 400, 300]

In this process we had three buttons and RGB diode. No mixing of colors were used so this 
behaviurs as three seperate diodes. 
The aim of the teacher was to pick one color and assign to the button on the breadboard. 
Whenever Arduino shows correct color after pushing the button, supervisor accept it 
with reward button.

As in this video learning time is very short so 60s to learn this basic schema with acceptable
level of success ratio was enought.
   

== Starting up

=== Hardware

=== Libraries

== Possiblities

== License

This work is licensed as GPL software. See LICENSE file for full text.

If you need other license or would like to get support, please contact me at marek.smigielski(at)gmail.com
